### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/ror-server#142]
This happens from time to time:
```
Thread 2433 "rorserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffc57656700 (LWP 21389)]
_int_malloc (av=av@entry=0x7fffec000020, bytes=bytes@entry=8208) at malloc.c:3789
3789	malloc.c: No such file or directory.
#0  _int_malloc (av=av@entry=0x7fffec000020, bytes=bytes@entry=8208) at malloc.c:3789
#1  0x00007ffff6d102ad in __GI___libc_malloc (bytes=8208) at malloc.c:3075
#2  0x00007ffff76b3298 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00005555555b4454 in __gnu_cxx::new_allocator<queue_entry_t>::allocate (__n=1, this=0x7ffd2ce9e9c8) at /usr/include/c++/7/ext/new_allocator.h:111
#4  std::allocator_traits<std::allocator<queue_entry_t> >::allocate (__n=1, __a=...) at /usr/include/c++/7/bits/alloc_traits.h:436
#5  std::_Deque_base<queue_entry_t, std::allocator<queue_entry_t> >::_M_allocate_node (this=0x7ffd2ce9e9c8) at /usr/include/c++/7/bits/stl_deque.h:602
#6  std::deque<queue_entry_t, std::allocator<queue_entry_t> >::_M_push_back_aux<queue_entry_t const&> (this=this@entry=0x7ffd2ce9e9c8) at /usr/include/c++/7/bits/deque.tcc:487
#7  0x00005555555b40a4 in std::deque<queue_entry_t, std::allocator<queue_entry_t> >::push_back (__x=..., this=0x7ffd2ce9e9c8) at /usr/include/c++/7/bits/stl_deque.h:1552
#8  Broadcaster::QueueMessage (this=0x7ffd2ce9e948, type=type@entry=1039, uid=<optimized out>, uid@entry=-1, streamid=<optimized out>, streamid@entry=4294967295, len=<optimized out>, data=0x7fffec4dcf90 "MOTD: #FFFF00Type !help to view available commands.") at /home/administrator/rorserver/source_243/source/server/broadcaster.cpp:138
#9  0x00005555555bea44 in Client::QueueMessage (this=<optimized out>, msg_type=msg_type@entry=1039, client_id=client_id@entry=-1, stream_id=stream_id@entry=4294967295, payload_len=<optimized out>, payload=<optimized out>) at /home/administrator/rorserver/source_243/source/server/sequencer.cpp:130
#10 0x00005555555c0cf8 in Sequencer::serverSay (this=this@entry=0x5555558f44e0 <s_sequencer>, msg="MOTD: #FFFF00Type !help to view available commands.", uid=uid@entry=1215, type=type@entry=2) at /home/administrator/rorserver/source_243/source/server/sequencer.cpp:611
#11 0x00005555555c0e9b in Sequencer::sendMOTD (this=0x5555558f44e0 <s_sequencer>, uid=1215) at /home/administrator/rorserver/source_243/source/server/sequencer.cpp:517
#12 0x00005555555bdb06 in Receiver::Thread (this=0x7ffd2ce9c918) at /home/administrator/rorserver/source_243/source/server/receiver.cpp:69
#13 0x00005555555bdc2a in LaunchReceiverThread (data=<optimized out>) at /home/administrator/rorserver/source_243/source/server/receiver.cpp:33
#14 0x00007ffff79b06db in start_thread (arg=0x7ffc57656700) at pthread_create.c:463
#15 0x00007ffff6d9a61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Petr comments:
> obvious race condition - a different thread modifies it in between
we lock m_queue_mutex there so someone must be forgetting to lock it when writing

**Comment by only-a-ptr** [comment]
Fixed by #145
